import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../styles/Home.module.css'
import { Layout } from "./components/navbar/Layout";
import NavBar from "./components/navbar/Navbar";
import FooterBar from "./components/footer";
import HomeOption from "./home"

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>COVID Statistics</title>
      </Head>
      <main className={styles.fontFamily}>
        <div>
          <Layout>
            <NavBar />
            <HomeOption />
            <FooterBar />
          </Layout>
        </div>
      </main>
    </>
  )
}
